[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "browser-use>=0.5.9",
    "langchain-openai>=1.0.1",
    "openai>=2.6.0",
    "playwright>=1.55.0",
    "python-dotenv>=1.1.1",
]
