[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "VisionVault - AI-Powered Browser Automation"
requires-python = ">=3.11"
dependencies = [
    "eventlet>=0.37.0",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "flask-socketio>=5.5.1",
    "gunicorn>=23.0.0",
    "openai>=2.1.0",
    "pillow>=11.3.0",
    "playwright>=1.55.0",
    "python-socketio>=5.14.1",
    "websocket-client>=1.8.0",
]
