[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.18.0",
    "openai>=2.6.0",
    "playwright>=1.55.0",
    "pydantic>=2.12.3",
    "rich>=14.2.0",
]
